<?php
// $Id$

/**
 * @file
 *   Publish RSS feeds for Watchdog.
 */

/**
 * Implementation of hook_help().
 */
function watchdog_rss_help($path, $arg) {
  $output = '';
  switch ($path) {
    case 'admin/help#watchdog_rss':
      $output = '<p>'. t('The Watchdog RSS module provides RSS feeds for Watchdog. ') .'</p>';
      break;
  }
  return $output;
}


/**
 * Implementation of hook_menu().
 */
function watchdog_rss_menu() {

  $items = array();

    $items['admin/settings/watchdog_rss'] = array(
      'title'     =>  'Watchdog RSS',
      'description' => 'Access / Change your site\'s Watchdog RSS Feed URL.',
      'page callback'  =>  'drupal_get_form',
      'page arguments' => array('watchdog_rss_admin_form'),
      'access arguments' => array('administer site configuration'),
	  'file' => 'watchdog_rss.admin.inc',
    );

    $items['watchdog-feed/'. variable_get('watchdog_rss_key', '')] = array(
      'title'     =>  'Watcdog RSS Feed',
      'page callback'  =>  'watchdog_rss_feed_site',
      'access arguments' => array('access content'),
	  'file' => 'watchdog_rss.feed.inc',
      'type'      =>  MENU_CALLBACK,
    );

  return $items;

}

/**
 * Implementing hook_init to enable Watchdog feed auto detection
 */
 function watchdog_rss_init() {
 
	 if (arg(2) === 'watchdog' && arg(1) === 'reports' && arg(0) === 'admin') {
      drupal_add_feed(
          url('watchdog-feed/'. variable_get('watchdog_rss_key', '')),
          t('@site - Watchdog Logs', array('@site' => variable_get('site_name', 'Drupal')))
      );
    }
 }


/**
 * Add New Permission to Allow People to View Watchdog RSS Feed
 *
 * @return void
 * @author Abhi
 */
function watchdog_rss_perm() {
  return array('access watchdog RSS feed');
}

/**
 * Provides a random string of the length requested.
 */
function watchdog_rss_random_gen($length) {
  $random= "";
  srand((double)microtime()*1000000);
  $char_list = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
  $char_list .= "abcdefghijklmnopqrstuvwxyz";
  $char_list .= "1234567890";

  for ($i = 0; $i < $length; $i++) {
    $random .= drupal_substr($char_list, (rand()%(drupal_strlen($char_list))), 1);
  }
  return $random;
}
